[[build]]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NEXT_PUBLIC_SUPABASE_URL = "https://otdcqhbcwzaekocarjor.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90ZGNxaGJjd3phZWtvY2Fyam9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzE3NzUsImV4cCI6MjA1ODkwNzc3NX0.tkOrPWdMhQxnS-GR08yN58fyo4tjw0fDFWIjC-O47bg" 