[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 개발 환경 설정
[context.develop]
  environment = { NODE_ENV = "development", NEXT_PUBLIC_API_URL = "https://develop.mcpkorea.com/api" }

# 스테이징 환경 설정
[context.staging]
  environment = { NODE_ENV = "staging", NEXT_PUBLIC_API_URL = "https://staging.mcpkorea.com/api" }

# 프로덕션 환경 설정
[context.production]
  environment = { NODE_ENV = "production", NEXT_PUBLIC_API_URL = "https://mcpkorea.com/api" }

# 리다이렉트 규칙
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 보안 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com" 