[build]
command = "npm run build"
publish = ".next"

# Next.js 프로젝트를 서버리스 함수로 배포하기 위한 설정
[[plugins]]
package = "@netlify/plugin-nextjs"

# 아래 리다이렉트 규칙은 Next.js 서버리스 함수와 함께 사용할 때 필요하지 않습니다
# [[redirects]]
# from = "/*"
# to = "/404.html"
# status = 404

# [[redirects]]
# from = "/*"
# to = "/index.html"
# status = 200 